### ISSUE TITLE
Can't get this to run on a Mac (M1, with python 3 installed)

### ISSUE THREAD

**Issue by SteveW25561** [cetteup/transfer-plex-user-viewstate#3]
I'm on a Mac, M1 Pro, I installed python3 (3.10.4) and pyenv (2.2.5)

but if I enter:

`python3 transfer-plex-user-viewstate.py -p ~/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases/com.plexapp.plugins.library.db`

I get a bunch of errors:

`Traceback (most recent call last):File "/Users/username/Desktop/transfer-plex-user-viewstate-main-1/transfer-plex-user-viewstate.py", line 5, in <module>from tabulate import tabulateFile "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tabulate.py", line 16, in <module>from collections import IterableImportError: cannot import name 'Iterable' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)`

I really have no idea what I'm doing!

**Comment by cetteup** [comment]
Quick question right off the bat: Did you install all the requirements?

**Comment by SteveW25561** [comment]
Yes, I did install the requirements:
```

pip3 install -r requirements.txt

Requirement already satisfied: altgraph==0.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.17)
Requirement already satisfied: tabulate==0.8.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.8.7)
```

**Comment by cetteup** [comment]
The issue was caused by an import in the `tabulate` library. They released a newer version which does not have the same issue when used with python 3.10.

Should work now if you run `git pull` followed `pip3 install -r requirements.txt` to install the newer version.
