### ISSUE TITLE
[1541332] Error loading Python lib '/home/nsc/transfer/libpython3.8.so.1.0': dlopen: /home/nsc/transfer/libpython3.8.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nsc80** [cetteup/transfer-plex-user-viewstate#6]
Hello.

I'm getting an error: `[1541332] Error loading Python lib '/home/nsc/transfer/libpython3.8.so.1.0': dlopen: /home/nsc/transfer/libpython3.8.so.1.0: cannot open shared object file: No such file or directory`

Ubuntu Server 22.04

Can you help?

Thank you

**Comment by cetteup** [comment]
Almost sounds like a broken Python install to me. Do other Python tools work fine?

Try running something simple like
```bash
python -c "print('Hello world')"
```
Also, what Python version are you using?

**Comment by nsc80** [comment]
I'm quite the noob in Linux. I don't use Python.

`nsc@winserver:~$ python -c "print('Hello world')"
Command 'python' not found, did you mean:  command 'python3' from deb python3 command 'python' from deb python-is-python3
nsc@winserver:~$ python3 -c "print('Hello world')"
Hello world`

libpython3-dev is already the newest version (3.10.6-1~22.04).

Thank you

**Comment by nsc80** [comment]
Well, I somehow got it. My bad
Sorry for the inconvenience and thank you for your time.

PS: This script is magic! Keep up the good work!

**Comment by cetteup** [comment]
Glad you got it working!
